=== MarianAmador/EsquemaXML/Canciones.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Canciones" type="CancionesType"/>
  <xs:complexType name="CompositorType">
    <xs:sequence>
      <xs:element name="Nombres" type="xs:string"/>
      <xs:element name="Apellidos" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CompositoresType">
    <xs:sequence>
      <xs:element type="CompositorType" name="Compositor" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProductorType">
    <xs:sequence>
      <xs:element name="Nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProductoresType">
    <xs:sequence>
      <xs:element type="ProductorType" name="Productor"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Canci칩nType">
    <xs:sequence>
      <xs:element name="Titulo" type="xs:string"/>
      <xs:element type="CompositoresType" name="Compositores"/>
      <xs:element type="ProductoresType" name="Productores"/>
      <xs:element name="Sello" type="xs:string"/>
      <xs:element name="Artista" type="xs:string"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="duracion" use="optional"/>
    <xs:attribute type="xs:string" name="a침o" use="optional"/>
  </xs:complexType>
  <xs:complexType name="CancionesType">
    <xs:sequence>
      <xs:element type="Canci칩nType" name="Canci칩n" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== MarianAmador/EsquemaXML/Canciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<Canciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Canciones.xsd">
    <Canción duracion="4:42" año="2022">
        <Titulo>Change</Titulo>

        <Compositores>
            <Compositor>
                <Nombres>Louis</Nombres>
                <Apellidos>Tomlinson</Apellidos>
            </Compositor>

            <Compositor>
                <Nombres>George</Nombres>
                <Apellidos>Tizzard</Apellidos>
            </Compositor>

            <Compositor>
                <Nombres>Rick</Nombres>
                <Apellidos>Parkhouse</Apellidos>
            </Compositor>

            <Compositor>
                <Nombres>Robert</Nombres>
                <Apellidos>Harvey</Apellidos>
            </Compositor>
        </Compositores>

        <Productores>
            <Productor>
                <Nombre>Red Triangle</Nombre>
            </Productor>
        </Productores>

        <Sello>BMG Publishing</Sello>
        <Artista>Louis Tomlinson</Artista>
    </Canción>

    <Canción duracion="2:48" año="2022">
        <Titulo>Valentine</Titulo>

        <Compositores>
            <Compositor>
                <Nombres>Laufey</Nombres>
            </Compositor>

            <Compositor>
                <Nombres>Spencer</Nombres>
                <Apellidos>Stewart</Apellidos>
            </Compositor>
        </Compositores>

        <Productores>
            <Productor>
                <Nombre>Spencer Stewart</Nombre>
            </Productor>
        </Productores>

        <Sello>Songtrust</Sello>
        <Artista>Laufey</Artista>
    </Canción>

    <Canción duracion="4:08" año="2014">
        <Titulo>18</Titulo>

        <Compositores>
            <Compositor>
                <Nombres></Nombres>
            </Compositor>

            <Compositor>
                <Nombres>Ed</Nombres>
                <Apellidos>Sheeran</Apellidos>
            </Compositor>

            <Compositor>
                <Nombres>Oliver</Nombres>
                <Apellidos>Frank</Apellidos>
            </Compositor>
        </Compositores>

        <Productores>
            <Productor>
                <Nombre>Steve Robson</Nombre>
            </Productor>
        </Productores>

        <Sello>Syco Music</Sello>
        <Artista>One Direction</Artista>
    </Canción>

    <Canción duracion="2:48" año="2022">
        <Titulo>Valentine</Titulo>
        <Compositores>
            <Compositor>
                <Nombres>Laufey</Nombres>
            </Compositor>

            <Compositor>
                <Nombres>Spencer</Nombres>
                <Apellidos>Stewart</Apellidos>
            </Compositor>
        </Compositores>

        <Productores>
            <Productor>
                <Nombre>Spencer Stewart</Nombre>
            </Productor>
        </Productores>

        <Sello>Songtrust</Sello>
        <Artista>Laufey</Artista>
    </Canción>
</Canciones>
